# ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
# ------------------------------------------------------------

###################################################################################################
# Package Secret Provider Class - CSI Driver
###################################################################################################
{{- $svcversion := .Chart.AppVersion | replace "." "" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: package-secrets-csi-akv-{{ $svcversion }}
  namespace: backend-dev
spec:
  provider: azure
  secretObjects:
  - secretName: package-secrets
    type: Opaque
    data:
    - objectName: CosmosDb--ConnectionString
      key: cosmosdb-connstr
    - objectName: ApplicationInsights--InstrumentationKey
      key: appinsights-ikey
    - objectName: ApplicationInsights--ConnectionString
      key: appinsights-connstr  
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.identity.clientid }}
    keyvaultName: {{ .Values.keyVaultName }}
    objects:  |
      array:
        - |
          objectName: CosmosDb--ConnectionString
          objectAlias: CosmosDb--ConnectionString
          objectType: secret
        - |
          objectName: ApplicationInsights--InstrumentationKey
          objectAlias: ApplicationInsights--InstrumentationKey
          objectType: secret 
        - |
          objectName: ApplicationInsights--ConnectionString
          objectAlias: ApplicationInsights--ConnectionString
          objectType: secret  
    tenantId: {{ .Values.identity.tenantId }}
---
