#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# Scheduler service
###################################################################################################
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: scheduler
  labels:
    app: scheduler 
    bc: shipping
    co: fabrikam
spec:
  serviceName: scheduler
  replicas: 32
  selector:
    matchLabels:
      app: scheduler 
  template:
    metadata:
      labels:
        app: scheduler 
        version: 0.1.0
        bc: shipping
        co: fabrikam
    spec:
      containers:
      - image:
        name: scheduler
        imagePullPolicy: IfNotPresent
        env:
          - name: HOST_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SERVICE_URI_ACCOUNT
            value: http://account/api/Account
          - name: SERVICE_URI_DELIVERY
            value: http://delivery/api/Deliveries
          - name: SERVICE_URI_DRONE
            value: http://dronescheduler/api/DroneDeliveries
          - name: SERVICE_URI_PACKAGE
            value: http://package/api/packages
          - name: SERVICE_URI_THIRDPARTY
            value: http://thirdparty/api/ThirdPartyDeliveries
          ## set this env to read from period of time
          ## otherwise is from last known checkpoint                              
          - name: CHECKPOINT_TIME_MINUTES
            value: "0"           
          - name: IOTHUB_EVENTHUB_NAME
            valueFrom:
              secretKeyRef: 
                name: scheduler-secrets
                key: eventhub_name 
          - name: IOTHUB_EVENTHUB_ENDPOINT
            valueFrom:
              secretKeyRef: 
                name: scheduler-secrets
                key: eventhub_sas_connection_string 
          - name: IOTHUB_ACCESS_CONNSTRING
            valueFrom:
              secretKeyRef: 
                name: scheduler-secrets
                key: eventhub_sas_connection_string
          - name: IOTHUB_CHECKPOINT_AZSTORAGE_ACCOUNT
            valueFrom:
              secretKeyRef: 
                name: scheduler-secrets
                key: storageaccount_name
          - name: IOTHUB_CHECKPOINT_AZSTORAGE_KEY
            valueFrom:
              secretKeyRef: 
                name: scheduler-secrets
                key: storageaccount_key
          - name: STORAGE_QUEUE_NAME
            value: "compensationqueue"
          - name: STORAGE_QUEUE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: scheduler-secrets
                key: queueconstring
          - name: IOTHUB_EVENTHUB_PARTITIONS
            value: "32"
          # Integration with l5d Daemon Sets
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: http_proxy
            value: $(NODE_NAME):4140
          - name: SERVICEMESH_HEADERS
            value: l5d-ctx-deadline,l5d-ctx-trace
          - name: SERVICEMESH_CORRELATION_HEADER
            value: l5d-ctx-trace
